export const ADD_TODO_ELEMENT = "ADD_TODO_ELEMENT";
export const DELETE_TODO_ELEMENT = "DELETE_TODO_ELEMENT";

export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const INVALID_USER = "INVALID_USER";
export const DELETE_CURRENT_USER = "DELETE_CURRENT_USER";
